[package]
name = "lol-accept-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tasklist = "0.2.13"
reqwest = { version = "0.11.24", features = ["blocking"] }
base64 = "0.13.0"
anyhow = "1.0"
tray-icon = "0.11.3"
image = "0.23.14"
winit = "0.29.13"
