[package]
name = "lol-accept"
version = "2.1.1"
edition = "2021"

[dependencies]
base64 = "0.13.0"
image = "0.23.14"
reqwest = { version = "0.11.24", features = ["blocking"] }
tasklist = "0.2.13"
tray-icon = "0.11.3"
winit = "0.29.13"

[build-dependencies]
winres = "0.1.12"
